language: cpp

compiler:
    - clang

before_script:
    - apt-get install libfuse-dev
    - git clone git://github.com/jedisct1/libsodium.git
    - cd libsodium
    - ./autogen.sh
    - ./configure --disable-dependency-tracking
    - sudo make install
    - sudo ldconfig
    - cd ..

script:
    - make
